baseURL: localhost
title: ch's Blog
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ['posts', 'papermod']
defaultContentLanguage: zh # é»˜è®¤è¯­è¨€

minify:
  disableXML: false
  minifyOutput: true

languages:
  zh:
    languageName: 'ä¸­æ–‡ğŸ‡¨ğŸ‡³'
    contentDir: content/Chinese
    params:
      profileMode:
        enabled: true # needs to be explicitly set
        title: 'æ­¤å»ç»å¹´ï¼Œåº”æ˜¯è‰¯è¾°å¥½æ™¯è™šè®¾'
        subtitle: 'æ¬¢è¿æ¥åˆ° ch çš„åšå®¢'
        imageUrl: '/images/dog.jpeg'
        imageWidth: 130
        imageHeight: 130
        imageTitle: my image
        buttons:
          - name: Posts
            url: post
      socialIcons:
        - name: x
          url: 'https://x.com/'
        - name: github
          url: 'https://github.com/Jundong-chan'
      analytics:
        google:
          SiteVerificationTag: 'XYZabc'
        bing:
          SiteVerificationTag: 'XYZabc'
        yandex:
          SiteVerificationTag: 'XYZabc'
      cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page
      editPost:
        URL: 'https://github.com/<path_to_repo>/content'
        Text: 'Suggest Changes' # edit text
        appendFilePath: true # to append file path to Edit link
      # for search
      # https://fusejs.io/api/options.html
      fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
        keys: ['title', 'permalink', 'summary', 'content']

    menu:
      main:
        - identifier: about
          name: å…³äº
          url: /about/
          weight: 1
        - identifier: blog
          name: åšå®¢
          url: /blog/
          weight: 2
        - identifier: projects
          name: é¡¹ç›®
          url: /projects/
          weight: 3

outputs:
  home:
    - HTML
    - RSS
    - JSON
