baseURL: https://copilotmoon.github.io
title: ch's Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

defaultContentLanguage: zh # é»˜è®¤è¯­è¨€
# defaultContentLanguageInSubdir: false # é»˜è®¤è¯­è¨€æ˜¯å¦æ”¾åœ¨å­ç›®å½•ä¸­


languages:
  zh: 
    languageName: "ä¸­æ–‡ğŸ‡¨ğŸ‡³"
    contentDir: content/Chinese
    profileMode:
      enabled: true # needs to be explicitly set
      title: 'æ­¤å»ç»å¹´ï¼Œåº”æ˜¯è‰¯è¾°å¥½æ™¯è™šè®¾'
      subtitle: 'This is the website of **CHASdk**. A Blog recods life and work.'
      imageUrl: '/images/cat.jpeg'
      imageWidth: 150
      imageHeight: 130
      imageTitle: my image
      buttons:
        - name: Posts
          url: posts
      menu:
        main:
          - identifier: about
            name: å…³äº 
            url: /about/
            weight: 1
          - identifier: blog
            name: åšå®¢
            url: /blog/
            weight: 2
          - identifier: projects
            name: é¡¹ç›®
            url: /projects/
            weight: 3
   

outputs:
    home:
      - HTML
      - RSS
      - JSON

  # é…ç½®æœç´¢å¼•æ“çš„å‚æ•°
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
 
  homeInfoParams:
    enabled: false # needs to be explicitly set
    Title: "Welcome! \U0001F44B"
    Content: "This is the website of **Chanin Nantasenamat, Ph.D.** and I create educational content on data science and bioinformatics.Some of you may know me as the **Data Professor**."
 # è”ç³»æ–¹å¼åœ°å€
  socialIcons:
    - name: x
      url: 'https://x.com/'
    - name: github
      url: 'https://github.com/Jundong-chan'
  

  analytics:
    google:
      SiteVerificationTag: 'XYZabc'
    bing:
      SiteVerificationTag: 'XYZabc'
    yandex:
      SiteVerificationTag: 'XYZabc'

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: 'https://github.com/<path_to_repo>/content'
    Text: 'Suggest Changes' # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ['title', 'permalink', 'summary', 'content']

# å¯¼èˆªæ çš„èœå•ï¼Œç›¸å…³å†…å®¹åœ¨ content ç›®å½•ä¸‹å®šä¹‰

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai
